### ISSUE TITLE
Death Brade

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#82] opened 2019-12-30 21:52 UTC
As soon as you start a fight, time is over. Maybe it has something to do with this? 

http://black-ship.net/~tukuyomi/snesemu/misc/bsnes_changelog.txt

>   - WRAM is now initialized to 0x55, SRAM to 0xff. Fixes Power Drive, Death Brade and RPM Racing

**Comment by SourMesen** [comment] 2019-12-30 22:08
Are you using the latest dev build?
This should be fixed by #67 

Edit: Although, might be useful to check rpm racing, too, since I didn't add any special case for that one.

**Comment by Max833** [comment] 2019-12-30 22:20
Hi Sour. I used this version:
![image](https://user-images.githubusercontent.com/53529402/71602864-73519980-2b5a-11ea-9c76-e49fbc18895c.png)

**Comment by SourMesen** [comment] 2020-01-02 23:57
I can't reproduce it here.  Maybe somehow your ROM is different?
If you look at the log window, what does the log look like when loading the file?  Should be something like this:
```
Game: DEATH BRADE
Game code: I�9�
Type: LoROM
Map Mode: $20
Rom Type: $00
File size: 1536 KB
```

The name being "DEATH BRADE" is what triggers the exception I've added to ensure the ram is initialized in such a way that the bug doesn't occur.  Also make sure you're not loading a save state (or clicking on it in the game selection screen, since that also loads a save state), or make sure you power cycle the game before testing it, to make sure it's initializing the RAM with something other than 0s.

Also gave R.P.M. racing a try, and it didn't seem to behave differently based on the ram init option, so I'm not sure what was supposed to be problematic about that one (e.g based on the changelog you quoted)

**Comment by Max833** [comment] 2020-01-06 12:04
Weird. The issue is gone now and I can play the game. R.P.M racing is looking good as well.
![image](https://user-images.githubusercontent.com/53529402/71817016-cbb9f700-3084-11ea-9ae7-d2f21852a3c8.png)

**Comment by SourMesen** [comment] 2020-01-07 23:51
The only thing I can think of is that an old save state was loaded, somehow (however unlikely that seems)
I'll close this for now - let me know if you see the bug again.

**Closed as completed by SourMesen** 2020-01-07 23:51 UTC
