### ISSUE TITLE
Bishoujo Senshi Sailor Moon - Another Story (Japan) - Static in Title Music with Random RAM

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#61] opened 2019-11-03 20:20 UTC
When you get to the title screen in this game, there is a noticeable static noise on a certain beat. This is with a freshly compiled win64 build of the libretro core. I wasn't initially able to replicate this in the latest stand alone Windows dev build, but the second time I booted the game I got a beeping sound on those beats instead of static. I booted it again after that and it seemed normal again. bsnes doesn't exhibit either anomaly. And I didn't notice any other music in the game having problems.

Attached is a recording of the static playing from the libretro build.

[smas Mesen-S Static.zip](https://github.com/SourMesen/Mesen-S/files/3802080/smas.Mesen-S.Static.zip)

**Comment by SourMesen** [comment] 2019-11-04 01:22
As far as I can tell, this is caused by the SPC's randomized RAM.  It's possible that the ram pattern needed to cause it is highly unlikely on real hardware, though (real RAM isn't perfectly random on power on, typically)

Try setting the power on state to All 0s or All 1s and see if you can reproduce it on your end (I haven't been able to).  Also, there was a bug with "All 0s" in libretro that caused it to use random ram anyway, that should be fixed now.

Looking at bsnes' code, it looks like the SPC's RAM is never randomized (I'm unsure if there's a hardware-related reason for that or not, though)

**Comment by Awakened0** [comment] 2019-11-04 04:18
All 0s and all 1s fix it in a fresh libretro build. All 1s works well with the Super Puyo Puyo 2 translation too, so I guess I'll leave it on that. I'll leave this open for now in case you think the randomization behavior should be changed.

**Comment by SourMesen** [comment] 2019-12-13 03:19
I added an override for this game that forces it to always init all ram bits to 1, which fixes the issue.

**Closed as completed by SourMesen** 2019-12-13 03:19 UTC
Labels: bug
