### ISSUE TITLE
Tile Viewer colors differ from actual palette

### ISSUE THREAD

**Issue by egrandizio** [SourMesen/Mesen-S#120] opened 2020-05-17 00:46 UTC
I was analyzing the tiles in F-ZERO and noticed an odd inconsistency.
Here's an example:

Let's examine the Dark Color from the energy barrier tiles:
![image](https://user-images.githubusercontent.com/65352263/82132992-4114a180-97b4-11ea-81fd-0e18479a9f7d.png)
![image](https://user-images.githubusercontent.com/65352263/82132985-2e01d180-97b4-11ea-831e-28651e8b64a1.png)
The hex code color is listed as 217B39 in the Palette Viewer.

If I take a screenshot of the game and use the dropper tool to get the color:
![image](https://user-images.githubusercontent.com/65352263/82133029-c13b0700-97b4-11ea-9224-b6425330275f.png)
![image](https://user-images.githubusercontent.com/65352263/82133040-c6985180-97b4-11ea-93c2-3f21abef4b7e.png)
It says 217B39, which is the same as the Palette Viewer.

The oddity comes in when I use the dropper tool on the tile in the Tile Viewer:
![image](https://user-images.githubusercontent.com/65352263/82133066-11b26480-97b5-11ea-87b6-512551e6889e.png)
This time, what should be the same color from the same tile shows up as 207838.

This slight color inconsistency is true for the other colors in the Tile Viewer as well. I would believe that it was just the result of some settings on my display if it weren't for the fact that the colors on the Game Window are consistent with the Palette Viewer, but not the Tile Viewer.

This difference seems to be unintentional, so I'm reporting it.

**Comment by SourMesen** [comment] 2020-05-17 05:07
Thanks!  This was caused by an older version of the 15-bit to 24-bit color conversion logic still being used by the ppu viewers, while the rest used the correct formulas.

This is fixed in the latest commit.

**Closed as completed by SourMesen** 2020-05-17 05:07 UTC
Labels: bug
