### ISSUE TITLE
Stable Star - Kyuusha Monogatari (Japan)

### ISSUE THREAD

**Issue by Max833** [SourMesen/Mesen-S#68] opened 2019-11-10 13:17 UTC
https://github.com/byuu/bsnes/issues/223

**Comment by SourMesen** [comment] 2019-11-11 00:24
Did you use 0.3.0 or the latest dev build?
I think the flashing is just a result of the bug I fixed in #59, and I can't reproduce it in the latest builds.  Can you check on your end?  (FYI, the dev builds are incorrectly numbered and still say 0.2.0.xx, even though they're newer than 0.3.0 - I fixed this earlier and the version should be 0.3.0.xx on the next dev build)

**Comment by Max833** [comment] 2019-11-11 07:34
Oh, yeah. I did use 0.3.0. I tried the latest build and it looks fine now. :)

**Closed as completed** 2019-11-11 07:35 UTC
