### ISSUE TITLE
[Libretro] Launching Content Sometimes Causes Retroarch to Minimize and Freeze

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen-S#103] opened 2020-02-29 23:16 UTC
This is a weird one and sometimes difficult to reproduce since it doesn't happen every time. So far I've only ever encountered it with the Mesen-S core. I'm testing on Windows 10 with a recent nightly RetroArch and Mesen-S core. I managed to get a [working log](https://pastebin.com/4HGrSdBU) and a [minimize/freeze log](https://pastebin.com/RZZLs72a) though, which should help.

For both of those logs, I launched the 240p test suite from Load Content in RetroArch and chose Mesen-S as the core to use. Then I pressed F to enter windowed mode and closed RA in both cases. In the minimized/frozen case, my cursor disappears after launching content and I have to alt+tab to my desktop or another open window to get it back. Then if I click on the RA icon in my taskbar, I get a black full screen with the pause icon in the top right. Pressing P to unpause doesn't work. I can press F to get into a window, but it's still frozen. I can press F1 to bring up the menu, but it freezes if I try to resume. Then I click the X on the window to close it. I don't get any Windows pop up about the application becoming unresponsive.

When I looked at a diff of the logs, these pause and framebuffer lines stood out to me (working on the left, minimize/frozen on the right):

![pauseframe](https://user-images.githubusercontent.com/4565863/75616285-32a3db80-5b1d-11ea-8e1f-272f996a661c.png)

So it looks like when the problem occurs, maybe it's launching with a tiny 4x4 framebuffer and it's causing a pause for some reason? Or the other way around...

So far I've been able to reproduce it with Vulkan and glcore, but not gl. I got it to happen once in Vulkan with shaders disabled too, just to rule a shader problem out.

@Ryunam actually ran into this issue with Beetle PSX software and mentioned it in the libretro Discord awhile back. I've never been able to reproduce it with that core though.

**Comment by SourMesen** [comment] 2020-03-01 00:59
I'm not quite sure what to make of this one - I haven't been able to reproduce it (but I haven't tried too hard to reproduce it, either.) How often does this happen?
As is, it looks more like it might be a retroarch issue than a core-specific issue (esp. if another core is known to sometimes have the same bug)

Looking at your logs, Mesen-S seems to be initializing the screen properly:
`[INFO] SET_GEOMETRY: 256x224, aspect: 1.301.`
Since SET_GEOMETRY only occurs once and says 256x224, I imagine the `[Vulkan filter chain]: Creating framebuffer 1024 x 1024` (or `4 x 4`) bits are values from RetroArch itself (e.g maybe based on window size, etc.) I have no idea where 4x4 could come from, but it doesn't look like it could come from my code ,at least.  Maybe Retroarch is resizing itself to 4x4 size when switching between windowed & fullscreen mode?

**Comment by Awakened0** [comment] 2020-03-01 01:31
Yeah, despite me not being able to repro it with Beetle PSX, it would make more sense if it was a frontend issue since someone else is running into it there too. It was happening pretty frequently when I was testing out audio settings with CT. Maybe around 1/3rd of the time? Though with the test suite ROM it's more like 4/5 times right now.

I reproduced it with a fresh nightly RetroArch.7z with the only settings I changed being switching the driver to Vulkan. So it's not any of my other custom settings. And it doesn't launch minimized when fullscreen isn't enabled; just freezes with a white screen in the window. [Here's a log from that setup.](https://pastebin.com/QVvKhwrS)

I'll close this and reopen it in the RetroArch repo since it seems to be a frontend Vulkan issue.

**Comment by Awakened0** [comment] 2020-03-26 05:51
I did some git bisecting:
```
857caa3e208d8bb3a5313db9d1fb29c485b67a8c is the first bad commit
commit 857caa3e208d8bb3a5313db9d1fb29c485b67a8c
Author: Sour <mesenemu@gmail.com>
Date:   Thu Dec 26 13:57:05 2019 -0500

    Input: Turn off hot plugging for directinput devices
    Loading a game or opening input config will still check for new DInput controllers

 Core/Console.cpp                  | 1 +
 UI/Forms/Config/frmInputConfig.cs | 4 ++++
 Windows/WindowsKeyManager.cpp     | 5 ++---
 3 files changed, 7 insertions(+), 3 deletions(-)
```
Even if this is a frontend issue, maybe this can help figure out what's triggering it.

**Comment by Awakened0** [comment] 2020-03-26 06:51
Ok, scratch that. I double checked the previous commit and found it bad this time, so I went through the bisect process again. This time launching 20 times without a freeze before marking a commit as good:
```
b5876ab8b1029ae63c41082413fb7e6440ef037a is the first bad commit
commit b5876ab8b1029ae63c41082413fb7e6440ef037a
Author: Sour <mesenemu@gmail.com>
Date:   Thu Dec 26 13:18:46 2019 -0500

    Debugger: Fixed edit breakpoint in SPC memory opening the wrong breakpoint window

 UI/Debugger/Config/HexEditorInfo.cs      |  7 ++-----
 UI/Debugger/MemoryTools/ctrlHexViewer.cs |  2 +-
 UI/Interop/DebugApi.cs                   | 13 +++++++++++++
 3 files changed, 16 insertions(+), 6 deletions(-)

```

**Comment by Awakened0** [comment] 2020-03-26 06:56
Arg, double checked the previous commit again and got a freeze. Guess this is a frontend issue.

**Comment by Awakened0** [comment] 2020-03-26 08:24
I tried checking out old versions of RetroArch dating back to August and couldn't find one that didn't freeze with the latest Mesen-S core. I ended up trying bisecting the core one more time and got this result:
```
5f2c502be9908b80ec359d96b09688f6917b8fda is the first bad commit
commit 5f2c502be9908b80ec359d96b09688f6917b8fda
Author: Sour <mesenemu@gmail.com>
Date:   Thu Dec 26 12:03:38 2019 -0500

    Run ahead support (+ improved save/load state performance)
    Note: Run ahead currently doesn't work well with netplay, movies and rewind

 Core/Console.cpp                               | 133 +++++++++++++++++--------
 Core/Console.h                                 |  13 ++-
 Core/ControlManager.cpp                        |   6 +-
 Core/Ppu.cpp                                   |   4 +
 Core/RewindManager.cpp                         |   4 +
 Core/SettingTypes.h                            |   2 +
 Core/SoundMixer.cpp                            |   2 +-
 Core/SystemActionManager.h                     |   4 +-
 Core/VideoDecoder.cpp                          |   8 ++
 UI/Config/EmulationConfig.cs                   |   2 +
 UI/Dependencies/resources.en.xml               |   4 +-
 UI/Forms/Config/frmEmulationConfig.Designer.cs | 133 +++++++++++++++++++------
 UI/Forms/Config/frmEmulationConfig.cs          |   1 +
 Utilities/Serializer.cpp                       |  83 ++++++++-------
 Utilities/Serializer.h                         |  23 ++---
 15 files changed, 300 insertions(+), 122 deletions(-)
```
This time I can't get it to freeze with the previous commit. And I double checked with a build at that runahead commit and got a freeze again. I haven't turned on runahead or rewind in RetroArch for any of my testing.

**Comment by Awakened0** [comment] 2020-03-26 21:36
I tried quite a few more times today with a build right before commit https://github.com/SourMesen/Mesen-S/commit/5f2c502be9908b80ec359d96b09688f6917b8fda and still can't get it to freeze. So that should be the first bad commit. I think it'd be fair to reopen this, since going back pretty far in RetroArch commits doesn't fix it but going before that core commit does.

**Comment by SourMesen** [comment] 2020-03-26 21:54
Sure, reopening is fine - though there isn't anything about that particular commit that strikes me as an obvious cause (the majority of the changes done in it should have no impact on the libretro core at all), so unless I can find a way to reproduce it on my end, fixing this one may be tricky.

**Comment by Awakened0** [comment] 2020-03-26 21:58
Yeah, I'm not sure how I'd even begin breaking that commit up into parts to try to narrow it down further myself.

**Comment by SourMesen** [comment] 2020-03-27 00:34
So, I think I might actually know what is causing it.

That commit adds a new member in Console.h:
`atomic<bool> _isRunAheadFrame;`
The value is not initialized - I keep making the mistake of assuming atomic<> stuff is initialized by default, but that's not the case.  I wouldn't be surprised if MSVC initializes it to false by default, and gcc/clang don't (thus making it random), which would explain why I can't reproduce it.

As a test, can you try adding this line:
`_isRunAheadFrame = false;`
at the top of Console::RunSingleFrame, here:
https://github.com/SourMesen/Mesen-S/blob/master/Core/Console.cpp#L236

This should make sure the flag is always turned off for libretro (rather than being random and never set to a proper value)

I've tried forcing the value to "true" on my end, and it does cause it to freeze on startup.

**Comment by Awakened0** [comment] 2020-03-27 04:20
Yeah, that looks like it fixed it. I launched 50 times with that line added without any freezes. Good sleuthing!

**Comment by SourMesen** [comment] 2020-03-27 23:58
Great - thanks for the confirmation!
Should be fixed now as of the latest commit.

**Closed as completed by SourMesen** 2020-03-27 23:58 UTC
Labels: bug

**Comment by Awakened0** [comment] 2020-03-28 00:13
Thanks again for the fix!
