### ISSUE TITLE
Crash on launch while attempting to load language resources

### ISSUE THREAD

**Issue by puigru** [SourMesen/Mesen-S#1] opened 2019-04-01 10:00 UTC
Windows system locale: es;Español (internacional)

![Error](https://user-images.githubusercontent.com/7153662/55319399-13b44980-5475-11e9-9132-49097761bcdb.png)

**Comment by SourMesen** [comment] 2019-04-01 11:16
Thanks for the report!
Should be fixed by 7d37cb3362e90f64a7d7d0f580402a3fa9a6389f, was caused by leftover code from Mesen which tried to load other resource files if the user profile isn't in English (which don't exist yet - keeping this as English-only for now, to avoid some of the overhead caused by supporting multiple languages)

**Comment by SourMesen** [comment] 2019-04-01 23:33
I've updated the zip/binary in the 0.1.0 release to include the fix - let me know if you still get issues after redownloading it.

**Closed as completed by SourMesen** 2019-04-01 23:33 UTC
Labels: bug

**Comment by puigru** [comment] 2019-04-03 21:31
Just tried it again. No issues and seems to have good compatibility. Nice work 👍
