### ISSUE TITLE
Load Random Game for folder

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen-S#106] opened 2020-03-29 15:39 UTC
Hi dear Sour,

Unlike Mesen, Loading a random game in Mesen-S is related to the recent games list unlike using the game's folder (specific folder or last folder used).

**Comment by SourMesen** [comment] 2020-03-30 00:57
I can't reproduce this.

Setting the "Games" folder to a specific folder (in Preferences -> Folders/Files -> Games) makes the random game option load games from that folder only.  Keeping it as "last folder only" will try to load random games from any recently used folder from the last 10 loaded games.

**Comment by ghost** [comment] 2020-03-30 13:39
Yes But the problem it's not loading random games (whether from specific folder or last folder).
It only loads the roms that they were loaded previously by the emulator.

For example we have a folder named (roms)
and it contains : rom1, rom2, rom3

Let's suppose we loaded rom1 , and then rom2 but not rom3
Now whenever I hit Random game , the emulator will only switch between rom1 and rom2
Whether the option is load from specific folder or last folder used.
it's not working like Mesen.

**Comment by ghost** [comment] 2020-03-30 13:51
Here is a demonstration
https://drive.google.com/file/d/1UpCnqRPXRpGhX2Ea9ChlnUq2oKZKcb0S/view

**Comment by SourMesen** [comment] 2020-03-30 21:00
Thanks for the video.

The problem is that the files in your folder are `.smc` files.  There was a small bug that caused the random game feature to ignore .smc files completely, which is why you got the "could not find any game" error. It should be fixed with the latest commit.

**Closed as completed by SourMesen** 2020-03-30 21:00 UTC
Labels: bug
